### ISSUE TITLE
Repo name clashes with mastodon repo

### ISSUE THREAD

**Issue by SuperSandro2000** [nextcloud/integration_mastodon#3]
You could rename it to nextcloud_mastodon or something like that.

**Comment by eneiluj** [comment]
At some point it's gonna be moved to "nextcloud" namespace. I didn't think it would catch the attention so fast :wink:.

**Comment by SuperSandro2000** [comment]
Then the name would still clash with github.com/tootsuite/mastodon like you saw with https://github.com/juliushaertl/mastodon-1
