### ISSUE TITLE
Open posts in the user's home instance?

### ISSUE THREAD

**Issue by BenDundon** [nextcloud/integration_mastodon#41]
Currently, posts and notifications open in the originating instance, rather than the user's home instance. This puts an unnecessary step between clicking on a post or notification, and interacting with it, as you then have to manually open it on your home instance. 

For example, if I am on `mymastodon.example`, and get a notification for a post from `greg@gregshome.space`, clicking on the post in my Nextcloud widget will take me to it on `gregshome.space` when it should really open in `mymastodon.example`. 

To make this happen, the way the URL is interpreted should be changed. A post's URL is formatted as
`http[s]://{original.server}/@{user}/{ID}`. When the post is not on the same server as it is being viewed from (i.e., when it is being viewed from a user's home instance), it is instead `http[s]://{other.server}/@{user}@{original.server}/{ID}`. By re-interpreting the URL before the user clicks on it, we can direct them to viewing the post/profile/notification from their own instance, rather than one they don't have an account on.

I'll work on a PR for this myself, but it's going to take me a while so if anyone wants to jump in with their own solution or comments then please do.

**Comment by julien-nc** [comment]
Thanks for the issue. This should be fixed in v1.0.5. Could you try it?

**Comment by kc9jud** [comment]
@julien-nc It works for the "home timeline" widget, but not for the "notifications" widget. Clicking on a notification of a reply opens the reply in the reply author's instance, rather than the user's instance.

**Comment by julien-nc** [comment]
Thanks for the feedback.
v1.0.6 should bring that for the notifications widget as well. Could you try it?

**Comment by BenDundon** [comment]
Yes, it seems to be working as intended now. Thank you very much!

**Comment by bear454** [comment]
:thinking: the links from the home timeline widget don't work for me; I always get a 404 page if I use any link except the "More..." link at the bottom.

For example, my widget currently links to:
https://social.librem.one/@nextcloud@mastodon.xyz/111109964371257104

... but to see that toot in the web UI of my home server, the link is actually:
https://social.librem.one/web/statuses/111109964371257104
