### ISSUE TITLE
bad character encoding on dashboard

### ISSUE THREAD

**Issue by ndx1905-github** [nextcloud/integration_mastodon#53]
Some characters are not displayed correctly in the French version of the dashboard. 
It should spell "Fil d'actualités Mastodon" as in the title and not "Fil d&#39;actualités Mastodon"
See screenshot
![tempsnip](https://github.com/nextcloud/integration_mastodon/assets/64833823/4be65557-ad8f-466d-8529-47e2ce3e8f43)

**Comment by andrey18106** [comment]
Hi! Thanks for reporting.

It's likely that the issue is in dashboard widget vue component (https://github.com/nextcloud-libraries/nextcloud-vue), not directly related to integration_mastodon, as the same translated string displayed in title of widget..

**Comment by susnux** [comment]
This issue is cause by this app, as it still uses the deprecated `@nextcloud/vue-dashboard` package for the dashboard widget.
Instead it should migrate to NcDashboard from `@nextcloud/vue`
