### ISSUE TITLE
Allow the use of custom Mastodon apps

### ISSUE THREAD

**Issue by nunesgh** [nextcloud/integration_mastodon#8]
Allow the use of a custom Mastodon app created by the Nextcloud admin.

A similar feature is already available for the Twitter, GitHub, and GitLab integrations.

**Comment by eneiluj** [comment]
As Mastodon allows anyone to declare an OAuth app, it is automatically done by the integration app before logging in.

What's the use case for having everyone using the same OAuth app?

**Comment by nunesgh** [comment]
I'm not sure whether we are talking about the same thing.

As you can see from the screenshot below, the Twitter integration app allows admins to use either their own Twitter OAuth app (maybe for privacy purposes) or the default Nextcloud Twitter OAuth app, provided by that repo's maintainer.

![image](https://user-images.githubusercontent.com/16168765/97315909-f3fb2800-1847-11eb-9596-888ed9883c18.png)

The Mastodon integration app only allows for the use of the default Nextcloud Mastodon OAuth app.

**Comment by eneiluj** [comment]
That's what I (badly :grin:) tried to explain. There is no default OAuth app used by Nextcloud (anyway it's impossible with a decentralized system as Mastodon). An OAuth app is automatically declared on the target server on-the-fly each time you ask the integration app to connect.

**Comment by nunesgh** [comment]
Now I get it! Thank you for sharing the information, @eneiluj!
