### ISSUE TITLE
Mastodon connection request is blocked on Firefox

### ISSUE THREAD

**Issue by sellerie98** [nextcloud/integration_mastodon#9]
Adding the Mastodon instance URL and clicking the "Connect to Mastodon" button does nothing in Firefox as the corresponding request is blocked by it.
It works fine on Chromium.
I have no idea how to debug this much further though.

**Comment by eneiluj** [comment]
Hi, thanks for the bug report.

* Is there any error in Firefox console? (F12 => Console tab)
* Which version of Firefox are you using?

> as the corresponding request is blocked by it

How do you see it's blocked? Is there a message somewhere?

**Comment by sellerie98** [comment]
The issues seemed to be my Firefox that blocked the request.
I found out after I could not access the website via Firefox at all anymore (it simply showed a "blocked" error for the request in the network tab of the devtools).
